%script that can be used to generate figure like Fig.4
 load DPOAEOPL150L250V4 %data created by e.g. Notas2JASAFig4_V05052025asymVysiLevely.m
 load pomocnedata x %coordinates along the BM in the longitudinal direction
 OPo=[-0.1:0.01:-0.05,-0.047:0.003:0,0,0.003:0.003:0.05,0.05:0.01:0.2];%OP shifts
 y=nonlin(OPo);%second order nonlinearity
 save pomocnedata y -append  
 ind=23;%zero OP shift ind=23;
 indp=3;
 indp2=6;

figure(1)
clf
subplot(2,2,1)
    semilogy(x,RRF1a(ind,:),'r',x,RRF2a(ind,:),'b',x,RRFdpa(ind,:),'k',...
        x,RRF1a(ind-indp,:),'r:',x,RRF2a(ind-indp,:),'b:',x,RRFdpa(ind-indp,:),'k:',...
        x,RRF1a(ind+indp,:),'r--',x,RRF2a(ind+indp,:),'b--',x,RRFdpa(ind+indp,:),'k--',...
        x,RRF1a(ind-indp2,:),'r-.',x,RRF2a(ind-indp2,:),'b-.',x,RRFdpa(ind-indp2,:),'k-.',...
        x,RRF1a(ind+indp2,:),'r-o',x,RRF2a(ind+indp2,:),'b-o',x,RRFdpa(ind+indp2,:),'k-o','MarkerSize',2)
    lgd=legend(num2str(OPo(ind)),num2str(OPo(ind)),num2str(OPo(ind)),...
          num2str(OPo(ind-indp)),num2str(OPo(ind-indp)),num2str(OPo(ind-indp)),...
          num2str(OPo(ind+indp)),num2str(OPo(ind+indp)),num2str(OPo(ind+indp)),...
          num2str(OPo(ind-indp2)),num2str(OPo(ind-indp2)),num2str(OPo(ind-indp2)),...
          num2str(OPo(ind+indp2)),num2str(OPo(ind+indp2)),num2str(OPo(ind+indp2)))
    lgd.Title.String='y_0'
    xlim([0,1.7])
    ylim([1E-9,5E-2])
    ylabel('BM amplitude [a.u.]')
    xlabel('Distance from stapes [cm]')

 subplot(2,2,3)
    plot(x,RRF1ph(ind,:),'r',x,RRF2ph(ind,:),'b',x,RRFdpph(ind,:),'k',...
        x,RRF1ph(ind-indp,:),'r:',x,RRF2ph(ind-indp,:),'b:',x,RRFdpph(ind-indp,:),'k:',...
        x,RRF1ph(ind+indp,:),'r--',x,RRF2ph(ind+indp,:),'b--',x,RRFdpph(ind+indp,:),'k--',...
        x,RRF1ph(ind-indp2,:),'r-.',x,RRF2ph(ind-indp2,:),'b-.',x,RRFdpph(ind-indp2,:),'k-.',...
        x,RRF1ph(ind+indp2,:),'r-o',x,RRF2ph(ind+indp2,:),'b-o',x,RRFdpph(ind+indp2,:),'k-o','MarkerSize',2)
   xlim([0,1.7])
   ylabel('BM phase [cycle]')
   xlabel('Distance from stapes [cm]')
subplot(2,2,2)
    semilogy(x,RRF1a(ind,:),'r',x,RRF2a(ind,:),'b',x,RRFdp2a(ind,:),'k',...
        x,RRF1a(ind-indp,:),'r:',x,RRF2a(ind-indp,:),'b:',x,RRFdp2a(ind-indp,:),'k:',...
        x,RRF1a(ind+indp,:),'r--',x,RRF2a(ind+indp,:),'b--',x,RRFdp2a(ind+indp,:),'k--',...
        x,RRF1a(ind-indp2,:),'r:',x,RRF2a(ind-indp2,:),'b:',x,RRFdp2a(ind-indp2,:),'k:',...
        x,RRF1a(ind+indp2,:),'r-o',x,RRF2a(ind+indp2,:),'b-o',x,RRFdp2a(ind+indp2,:),'k-o','MarkerSize',2)
    % legend(num2str(OPo(ind)),num2str(OPo(ind)),num2str(OPo(ind)),...
    %       num2str(OPo(ind-indp)),num2str(OPo(ind-indp)),num2str(OPo(ind-indp)),...
    %       num2str(OPo(ind+indp)),num2str(OPo(ind+indp)),num2str(OPo(ind+indp)),...
    %       num2str(OPo(ind-indp2)),num2str(OPo(ind-indp2)),num2str(OPo(ind-indp2)),...
    %       num2str(OPo(ind+indp2)),num2str(OPo(ind+indp2)),num2str(OPo(ind+indp2)))
    xlim([0,2.5])
     ylim([1E-9,5E-2])
     ylabel('BM amplitude [a.u.]')
    xlabel('Distance from stapes [cm]')

 subplot(2,2,4)
    plot(x,RRF1ph(ind,:),'r',x,RRF2ph(ind,:),'b',x,RRFdp2ph(ind,:),'k',...
        x,RRF1ph(ind-indp,:),'r:',x,RRF2ph(ind-indp,:),'b:',x,RRFdp2ph(ind-indp,:),'k:',...
        x,RRF1ph(ind+indp,:),'r--',x,RRF2ph(ind+indp,:),'b--',x,RRFdp2ph(ind+indp,:),'k--',...
        x,RRF1ph(ind-indp2,:),'r:',x,RRF2ph(ind-indp2,:),'b:',x,RRFdp2ph(ind-indp2,:),'k:',...
        x,RRF1ph(ind+indp2,:),'r-o',x,RRF2ph(ind+indp2,:),'b-o',x,RRFdp2ph(ind+indp2,:),'k-o','MarkerSize',2)
   xlabel('Distance from stapes [cm]')
   ylabel('BM phase [cycle]')
    
    xlim([0,2.5])   

    
  %  y=nonlin(OPo);
    figure(101)
plot(OPo,y,'k',OPo(ind),y(ind),'ko',...
    OPo(ind-indp2),y(ind-indp2),'ro',OPo(ind-indp),y(ind-indp),'bo',...
    OPo(ind+indp),y(ind+indp),'go',OPo(ind+indp2),y(ind+indp2),'co','LineWidth',2)
grid on
xlim([OPo(1),OPo(end)])